spring:
  application:
    name: namingserver
  config:
    import: "optional:configserver:http://localhost:8888"
  profiles:
    active: default
  main:
    banner-mode: off

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false


management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}