spring:
  application:
    name: "configServer"
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/omarhashem80/e-commerce-config.git"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true

  main:
    banner-mode: off


server:
  port: 8888