spring:
  application:
    name: "configServer"
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/omarhashem80/e-commerce-config.git"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true

  main:
    banner-mode: off


server:
  port: 8888


management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

encrypt:
  key: "45D81EC1EF61DF9AD8D3E5BB397F9"